"""IT-J5 — one request, one trace id, one story told by three systems.

Observability is not "the components emit telemetry". It is that a person
holding a single identifier can follow a request across every process it
touched, see it counted in the same place their dashboard reads from, and get
the same verdict from the readiness endpoint that the alert is based on. Any of
those three can be true while the others are not, so all three are asserted
here against the *same* piece of traffic.

The trace id is generated by this module rather than read back from a response.
That is the difference between proving propagation and proving that something
somewhere makes up an id: the value asserted at the far end of the pipeline is
the value the caller chose.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import httpx
import pytest
import stack
from stack import Airflow, Prometheus, TraceBackend

pytestmark = [
    pytest.mark.integration,
    pytest.mark.matrix("IT-J5-trace-metrics-continuity"),
]

INGEST_ROUTE = "/api/v1/feedback"

#: Spans on the path a caller waits for.
SYNCHRONOUS_LEG = [
    "lab28.gateway.request",
    "lab28.api.ingest",
    "lab28.kafka.produce",
]
#: Spans produced after the 202, by processes the caller never talks to.
ASYNCHRONOUS_LEG = [
    "lab28.kafka.consume",
    "lab28.airflow.dag",
    "lab28.spark.delta_merge",
]
#: Spans of the serving path, only reachable with a real inference endpoint.
SERVING_LEG = [
    "lab28.api.ask",
    "lab28.mlflow.resolve_release",
    "lab28.qdrant.query",
    "lab28.feast.get_online_features",
    "lab28.vllm.chat_completion",
]


@dataclass
class Traffic:
    trace_id: str
    traceparent: str
    asker_id: str
    ingest: httpx.Response
    readiness: httpx.Response
    dag_run: dict[str, Any]


def _collector_metric(prometheus: Prometheus, name: str) -> float | None:
    """Read a collector self-metric under either of the two names it ships as.

    The OpenTelemetry Collector's own counters gained the ``_total`` suffix when
    its internal telemetry moved to the OTLP conventions, and which one a stack
    exposes depends on the collector version. The matrix names the base series,
    so both are accepted rather than pinning the suite to one build.
    """
    for candidate in (name, f"{name}_total"):
        value = prometheus.value(f"sum({candidate})")
        if value is not None:
            return value
    return None


@pytest.fixture(scope="module")
def traffic(gateway: httpx.Client, airflow: Airflow) -> Traffic:
    """One ingestion, carried end to end under a trace id this module chose."""
    suffix = stack.run_id()
    trace_id, traceparent = stack.new_trace()
    asker_id = f"it-j5-{suffix}"

    readiness = gateway.get("/ready")
    ingest = gateway.post(
        INGEST_ROUTE,
        json={
            "asker_id": asker_id,
            "text": f"Phản hồi dùng để kiểm tra tính liên tục của trace {suffix}.",
            "rating": 5,
            "label": "positive",
        },
        headers={"traceparent": traceparent},
    )
    assert ingest.status_code == 202, ingest.text

    dag_run = airflow.wait_for_run(
        airflow.trigger(conf={"traceparent": traceparent}, note=f"IT-J5 continuity {suffix}")
    )

    return Traffic(
        trace_id=trace_id,
        traceparent=traceparent,
        asker_id=asker_id,
        ingest=ingest,
        readiness=readiness,
        dag_run=dag_run,
    )


@pytest.fixture(scope="module")
def answer(gateway: httpx.Client, traffic: Traffic) -> dict[str, Any]:
    """The serving leg of the same trace. Only requested by gpu-marked tests."""
    response = gateway.post(
        "/api/v1/ask",
        json={
            "asker_id": traffic.asker_id,
            "question": "Nền tảng dữ liệu của lab này gồm những thành phần nào?",
            "top_k": 3,
        },
        headers={"traceparent": traffic.traceparent},
        timeout=90.0,
    )
    assert response.status_code == 200, response.text
    return dict(response.json())


# -- IP08: the gateway --------------------------------------------------------


def test_the_gateway_stamps_a_request_id_on_what_it_proxies(traffic: Traffic) -> None:
    """The id that ties a gateway access log line to an application log line."""
    for response in (traffic.readiness, traffic.ingest):
        assert response.headers.get("x-request-id"), dict(response.headers)


def test_the_caller_trace_context_survives_the_proxy(traffic: Traffic) -> None:
    """A proxy that starts a fresh trace breaks every downstream correlation."""
    assert traffic.ingest.headers.get("x-lab28-trace-id") == traffic.trace_id


# -- IP09: metrics ------------------------------------------------------------


def test_the_request_is_counted_where_the_dashboard_reads(
    prometheus: Prometheus, traffic: Traffic
) -> None:
    """Scraped from Prometheus, not from /metrics: the gap between them is real."""
    counted = stack.wait_until(
        "Prometheus to scrape the ingestion route counter",
        lambda: prometheus.value(f'sum(lab28_requests_total{{route="{INGEST_ROUTE}"}})'),
        timeout=90.0,
        interval=5.0,
    )

    assert counted >= 1, f"the accepted request was never counted: {counted}"


def test_the_latency_of_that_request_is_observable(
    prometheus: Prometheus, traffic: Traffic
) -> None:
    """A counter says it happened; a histogram is what an SLO can be written against."""
    observed = stack.wait_until(
        "Prometheus to scrape the latency histogram",
        lambda: prometheus.value(f'sum(lab28_request_seconds_count{{route="{INGEST_ROUTE}"}})'),
        timeout=90.0,
        interval=5.0,
    )

    assert observed >= 1


def test_the_readiness_verdict_is_visible_as_a_gauge(
    api: httpx.Client, prometheus: Prometheus
) -> None:
    """The alert and the endpoint must not be able to disagree.

    ``/ready`` is called first on purpose: the per-component gauges are set when
    the probe runs, so an alert on them is only as fresh as the last check.
    """
    response = api.get("/ready")
    status_code, body = response.status_code, response.json()
    reported = {
        component["name"]: component["ready"] for component in body["components"]
    }

    def matching_gauges() -> dict[str, bool] | None:
        series = prometheus.query("lab28_component_ready")
        published = {
            entry["metric"]["component"]: float(entry["value"][1]) == 1.0 for entry in series
        }
        if set(reported) <= set(published) and all(
            published[name] == ready for name, ready in reported.items()
        ):
            return published
        return None

    published = stack.wait_until(
        "Prometheus to scrape the component readiness gauges matching /ready",
        matching_gauges,
        timeout=90.0,
        interval=2.0,
    )

    assert set(reported) <= set(published), (
        f"components missing from the gauge: {sorted(set(reported) - set(published))}"
    )
    assert (status_code == 503) == (body["status"] == "not_ready")
    for name, ready in reported.items():
        assert published[name] == ready, f"{name}: /ready says {ready}, Prometheus says otherwise"


# -- IP10: the trace ----------------------------------------------------------


def test_the_synchronous_leg_is_one_trace(traces: TraceBackend, traffic: Traffic) -> None:
    """Gateway, API and producer, under the id the caller supplied."""
    names = traces.wait_for_spans(traffic.trace_id, SYNCHRONOUS_LEG, timeout=120.0)

    assert set(SYNCHRONOUS_LEG) <= names


def test_the_asynchronous_leg_joins_the_same_trace(
    matrix: dict[str, Any], traces: TraceBackend, traffic: Traffic
) -> None:
    """The hard half: nothing carries context across Kafka unless it was written there.

    The consumer, the DAG and the merge run in three processes that never saw
    the caller's request, so a shared trace id here can only have come from the
    message headers and the run configuration.
    """
    names = traces.wait_for_spans(traffic.trace_id, ASYNCHRONOUS_LEG, timeout=240.0)
    required = set(matrix["required_spans"])

    stack.write_evidence(
        "ip10-trace.json",
        {
            "trace_id": traffic.trace_id,
            "traceparent": traffic.traceparent,
            "dag_run_id": traffic.dag_run.get("dag_run_id"),
            "span_count": len(traces.spans(traffic.trace_id)),
            "span_names": sorted(names),
            "services": sorted(traces.service_names(traffic.trace_id)),
            "required_spans_present": sorted(required & names),
            "required_spans_missing": sorted(required - names),
        },
    )

    assert set(ASYNCHRONOUS_LEG) <= names


def test_the_trace_crosses_process_boundaries(
    traces: TraceBackend, traffic: Traffic
) -> None:
    """One service reporting every span means the context never actually left it."""
    services = traces.service_names(traffic.trace_id)

    assert len(services) >= 3, f"only {sorted(services)} reported spans on this trace"


@pytest.mark.gpu
def test_the_serving_leg_joins_the_same_trace(
    traces: TraceBackend, traffic: Traffic, answer: dict[str, Any]
) -> None:
    """Registry, retrieval, features and inference, all under the caller's id."""
    assert answer["evidence"]["trace_id"] == traffic.trace_id

    names = traces.wait_for_spans(traffic.trace_id, SERVING_LEG, timeout=180.0)

    assert set(SERVING_LEG) <= names


def test_the_collector_exported_every_span_it_accepted(
    prometheus: Prometheus, traffic: Traffic
) -> None:
    """Spans that reach the collector and stop there look identical to spans never sent."""
    sent = stack.wait_until(
        "the collector to report exported spans",
        lambda: _collector_metric(prometheus, "otelcol_exporter_sent_spans"),
        timeout=90.0,
        interval=5.0,
    )
    failed = _collector_metric(prometheus, "otelcol_exporter_send_failed_spans")

    assert sent > 0
    # A counter that has never been incremented has no series at all, which for
    # this one is the same statement as zero.
    assert not failed, f"the collector failed to export {failed} spans"
